<div id='left'>
	<div id='cssmenu'>
		<center>
			<a href='http://delphigl.de/glcapsviewer/listreports2.php?sortby=date_desc'><img src='opengl-logo.gif' width=150px></img></a><br>
			Hardware database
		</center>
		<ul>
		   <li class='active'><a href='#'><span>List</span></a></li>
			   <li class='has_sub' style="font-size:12px; padding-left:20px;"><a href='./listreports2.php?sortby=date_desc'><span>Reports</span></a></li>
				   <li class='has_sub' style="font-size:12px; padding-left:30px;"><a href='./listreports2.php?groupby=renderer'><span>By Renderer</span></a></li>
				   <li class='has_sub' style="font-size:12px; padding-left:30px;"><a href='./listreports2.php?groupby=version'><span>By Version</span></a></li>
				   <li class='has_sub' style="font-size:12px; padding-left:30px;"><a href='./listreports2.php?groupby=os'><span>By OS</span></a></li>
			   <li class='active_inset' style="font-size:12px; padding-left:20px;"><a href='./gl_extensions.php'><span>Extensions</span></a></li>
			   <li class='active_inset' style="font-size:12px; padding-left:20px;"><a href='./gl_stats_caps.php'><span>Capabilities</span></a></li>
		   <li class='active'><a href="#"><span>Statistics</span></a></li>
			   <li class='active_inset' style="font-size:12px; padding-left:20px;"><a href='./gl_stats_versions.php'><span>Version coverage</span></a></li>
			   <li class='active_inset' style="font-size:12px; padding-left:20px;"><a href='./gl_stats_maxsupportedversions.php'><span>Version support</span></a></li>
		   <li class='has-sub'><a href='http://www.saschawillems.de/?page_id=771'><span>Download</span></a>
		   <li><a href='./gl_news.php'><span>News</span></a></li>
		   <li><a href='./gl_about.php'><span>About</span></a></li>
		   <li><a href='./gl_donate.php'><span>Donate</span></a></li>
		</ul>
	</div>
</div>
