/** 		
 *
 * OpenGL hardware capability database MySQL database structure
 *
 * Copyright (C) 2021 by Sascha Willems (www.saschawillems.de)
 *	
 * This code is free software, you can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public
 * License version 3 as published by the Free Software Foundation.
 *	
 * Please review the following information to ensure the GNU Lesser
 * General Public License version 3 requirements will be met:
 * http://www.gnu.org/licenses/agpl-3.0.de.html
 *	
 * The code is distributed WITHOUT ANY WARRANTY; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE.  See the GNU AGPL 3.0 for more details.		
 *
 */

 CREATE TABLE `compressedTextureFormats` (
  `reportId` int(11) NOT NULL,
  `formatEnum` int(11) NOT NULL,
  PRIMARY KEY (`reportId`,`formatEnum`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `enumTranslationTable` (
  `enum` int(11) NOT NULL,
  `text` text NOT NULL,
  PRIMARY KEY (`enum`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `intFormatProps` (
  `intFormatId` int(11) NOT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` text,
  `value` int(11) DEFAULT NULL,
  PRIMARY KEY (`intFormatId`,`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `intFormatTargets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`,`name`),
  UNIQUE KEY `name_UNIQUE` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;

CREATE TABLE `intFormats` (
  `reportId` int(11) NOT NULL,
  `targetId` int(11) NOT NULL,
  `formatId` int(11) NOT NULL AUTO_INCREMENT,
  `name` text,
  `supported` int(11) DEFAULT NULL,
  PRIMARY KEY (`formatId`,`reportId`,`targetId`)
) ENGINE=MyISAM AUTO_INCREMENT=5041 DEFAULT CHARSET=latin1;

CREATE TABLE `internalFormatInformation` (
  `reportId` int(11) NOT NULL,
  `target` text,
  `format` text,
  `supported` int(11) DEFAULT NULL,
  `property` text,
  `value` int(11) DEFAULT NULL,
  `rowId` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`rowId`,`reportId`)
) ENGINE=MyISAM AUTO_INCREMENT=8582 DEFAULT CHARSET=latin1;

CREATE TABLE `openglcaps` (
  `ReportID` int(11) NOT NULL AUTO_INCREMENT,
  `description` text CHARACTER SET utf8 NOT NULL,
  `appversion` text CHARACTER SET utf8 NOT NULL,
  `fileversion` text CHARACTER SET utf8 NOT NULL,
  `GL_VENDOR` text CHARACTER SET utf8 NOT NULL,
  `GL_RENDERER` text CHARACTER SET utf8 NOT NULL,
  `GL_VERSION` text CHARACTER SET utf8 NOT NULL,
  `os` text CHARACTER SET utf8 NOT NULL,
  `submitter` text CHARACTER SET utf8 NOT NULL,
  `comment` varchar(64) DEFAULT NULL,
  `contexttype` varchar(20) DEFAULT NULL,
  `GL_SHADING_LANGUAGE_VERSION` text CHARACTER SET utf8 NOT NULL,
  `GL_MAX_COLOR_ATTACHMENTS` int(11) DEFAULT NULL,
  `GL_MAX_SAMPLES` int(11) DEFAULT NULL,
  `GL_MAX_TEXTURE_SIZE` int(11) DEFAULT NULL,
  `GL_MAX_3D_TEXTURE_SIZE` int(11) DEFAULT NULL,
  `GL_MAX_CUBE_MAP_TEXTURE_SIZE` int(11) DEFAULT NULL,
  `GL_MAX_TEXTURE_LOD_BIAS` int(11) DEFAULT NULL,
  `GL_MAX_ARRAY_TEXTURE_LAYERS` int(11) DEFAULT NULL,
  `GL_MAX_TEXTURE_BUFFER_SIZE` int(11) DEFAULT NULL,
  `GL_MAX_RECTANGLE_TEXTURE_SIZE` int(11) DEFAULT NULL,
  `GL_MAX_RENDERBUFFER_SIZE` int(11) DEFAULT NULL,
  `GL_MAX_VIEWPORT_DIMS[0]` int(11) DEFAULT NULL,
  `GL_MAX_VIEWPORT_DIMS[1]` int(11) DEFAULT NULL,
  `GL_MAX_LIGHTS` int(11) DEFAULT NULL,
  `GL_MAX_CLIP_PLANES` int(11) DEFAULT NULL,
  `GL_MAX_MODELVIEW_STACK_DEPTH` int(11) DEFAULT NULL,
  `GL_MAX_PROJECTION_STACK_DEPTH` int(11) DEFAULT NULL,
  `GL_MAX_TEXTURE_STACK_DEPTH` int(11) DEFAULT NULL,
  `GL_MAX_ATTRIB_STACK_DEPTH` int(11) DEFAULT NULL,
  `GL_MAX_COLOR_MATRIX_STACK_DEPTH` int(11) DEFAULT NULL,
  `GL_MAX_LIST_NESTING` int(11) DEFAULT NULL,
  `GL_SUBPIXEL_BITS` int(11) DEFAULT NULL,
  `GL_MAX_ELEMENTS_INDICES` int(11) DEFAULT NULL,
  `GL_MAX_ELEMENTS_VERTICES` int(11) DEFAULT NULL,
  `GL_MAX_TEXTURE_UNITS` int(11) DEFAULT NULL,
  `GL_MAX_TEXTURE_COORDS` int(11) DEFAULT NULL,
  `GL_MAX_SAMPLE_MASK_WORDS` int(11) DEFAULT NULL,
  `GL_MAX_COLOR_TEXTURE_SAMPLES` int(11) DEFAULT NULL,
  `GL_MAX_DEPTH_TEXTURE_SAMPLES` int(11) DEFAULT NULL,
  `GL_MAX_INTEGER_SAMPLES` int(11) DEFAULT NULL,
  `GL_MAX_VERTEX_ATTRIBS` int(11) DEFAULT NULL,
  `GL_MAX_VERTEX_UNIFORM_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_DRAW_BUFFERS` int(11) DEFAULT NULL,
  `GL_MAX_VERTEX_UNIFORM_VECTORS` int(11) DEFAULT NULL,
  `GL_MAX_VERTEX_UNIFORM_BLOCKS` int(11) DEFAULT NULL,
  `GL_MAX_VERTEX_OUTPUT_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS` int(11) DEFAULT NULL,
  `GL_MAX_FRAGMENT_UNIFORM_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_FRAGMENT_UNIFORM_VECTORS` int(11) DEFAULT NULL,
  `GL_MAX_FRAGMENT_UNIFORM_BLOCKS` int(11) DEFAULT NULL,
  `GL_MAX_FRAGMENT_INPUT_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_TEXTURE_IMAGE_UNITS` int(11) DEFAULT NULL,
  `GL_MIN_PROGRAM_TEXEL_OFFSET` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_TEXEL_OFFSET` int(11) DEFAULT NULL,
  `GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET` int(11) DEFAULT NULL,
  `GL_MAX_UNIFORM_BUFFER_BINDINGS` int(11) DEFAULT NULL,
  `GL_MAX_UNIFORM_BLOCK_SIZE` int(11) DEFAULT NULL,
  `GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT` int(11) DEFAULT NULL,
  `GL_MAX_COMBINED_UNIFORM_BLOCKS` int(11) DEFAULT NULL,
  `GL_MAX_VARYING_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_VARYING_VECTORS` int(11) DEFAULT NULL,
  `GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS` int(11) DEFAULT NULL,
  `GL_MAX_SUBROUTINES` int(11) DEFAULT NULL,
  `GL_MAX_SUBROUTINE_UNIFORM_LOCATIONS` int(11) DEFAULT NULL,
  `GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_VARYING_FLOATS` int(11) DEFAULT NULL,
  `GL_MAX_GEOMETRY_UNIFORM_BLOCKS` int(11) DEFAULT NULL,
  `GL_MAX_GEOMETRY_INPUT_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_GEOMETRY_OUTPUT_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_GEOMETRY_OUTPUT_VERTICES` int(11) DEFAULT NULL,
  `GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS` int(11) DEFAULT NULL,
  `GL_MAX_GEOMETRY_SHADER_INVOCATIONS` int(11) DEFAULT NULL,
  `GL_MAX_VERTEX_STREAMS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_GEN_LEVEL` int(11) DEFAULT NULL,
  `GL_MAX_PATCH_VERTICES` int(11) DEFAULT NULL,
  `GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_VALUATION_UNIFORM_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_PATCH_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_CONTROL_INPUT_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS` int(11) DEFAULT NULL,
  `GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS` int(11) DEFAULT NULL,
  `GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_TRANSFORM_FEEDBACK_BUFFERS` int(11) DEFAULT NULL,
  `extensions` text CHARACTER SET utf8 NOT NULL,
  `submissiondate` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `note` text,
  `GL_MAJOR_VERSION` int(11) DEFAULT NULL,
  `GL_MINOR_VERSION` int(11) DEFAULT NULL,
  `GL_NUM_SHADING_LANGUAGE_VERSIONS` int(11) DEFAULT NULL,
  `GL_MAX_FRAGMENT_INTERPOLATION_OFFSET` int(11) DEFAULT NULL,
  `GL_MIN_FRAGMENT_INTERPOLATION_OFFSET` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_TEXTURE_GATHER_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MIN_SAMPLE_SHADING_VALUE` int(11) DEFAULT NULL,
  `GL_MIN_MAP_BUFFER_ALIGNMENT` int(11) DEFAULT NULL,
  `GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS` int(11) DEFAULT NULL,
  `GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE` int(11) DEFAULT NULL,
  `GL_MAX_COMBINED_ATOMIC_COUNTERS` int(11) DEFAULT NULL,
  `GL_MAX_FRAGMENT_ATOMIC_COUNTERS` int(11) DEFAULT NULL,
  `GL_MAX_GEOMETRY_ATOMIC_COUNTERS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS` int(11) DEFAULT NULL,
  `GL_MAX_VERTEX_ATOMIC_COUNTERS` int(11) DEFAULT NULL,
  `GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS` int(11) DEFAULT NULL,
  `GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS` int(11) DEFAULT NULL,
  `GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS` int(11) DEFAULT NULL,
  `GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS` int(11) DEFAULT NULL,
  `GL_MAX_GEOMETRY_UNIFORM_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_VERTEX_ATTRIB_STRIDE` int(11) DEFAULT NULL,
  `GL_MAX_GEOMETRY_VARYING_COMPONENTS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_VERTEX_VARYING_COMPONENTS_ARB` int(11) DEFAULT NULL,
  `GL_NUM_SHADER_BINARY_FORMATS` int(11) DEFAULT NULL,
  `GL_MAX_ELEMENT_INDEX` int(11) DEFAULT NULL,
  `GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET` int(11) DEFAULT NULL,
  `GL_MAX_VERTEX_ATTRIB_BINDINGS` int(11) DEFAULT NULL,
  `GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES` int(11) DEFAULT NULL,
  `GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS` int(11) DEFAULT NULL,
  `GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS` int(11) DEFAULT NULL,
  `GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS` int(11) DEFAULT NULL,
  `GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS` int(11) DEFAULT NULL,
  `GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS` int(11) DEFAULT NULL,
  `GL_MAX_SHADER_STORAGE_BLOCK_SIZE` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_SHARED_MEMORY_SIZE` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_UNIFORM_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_ATOMIC_COUNTERS` int(11) DEFAULT NULL,
  `GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_UNIFORM_BLOCKS` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_IMAGE_UNIFORMS` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_WORK_GROUP_COUNT[0]` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_WORK_GROUP_COUNT[1]` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_WORK_GROUP_COUNT[2]` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_WORK_GROUP_SIZE[0]` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_WORK_GROUP_SIZE[1]` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_WORK_GROUP_SIZE[2]` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_FIXED_GROUP_INVOCATIONS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_FIXED_GROUP_SIZE_ARB` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_VARIABLE_GROUP_INVOCATIONS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_COMPUTE_VARIABLE_GROUP_SIZE_ARB` int(11) DEFAULT NULL,
  `GL_MAX_DEBUG_MESSAGE_LENGTH_ARB` int(11) DEFAULT NULL,
  `GL_MAX_DEBUG_LOGGED_MESSAGES_ARB` int(11) DEFAULT NULL,
  `GL_MAX_DEBUG_GROUP_STACK_DEPTH` int(11) DEFAULT NULL,
  `GL_MAX_LABEL_LENGTH` int(11) DEFAULT NULL,
  `GL_MAX_DRAW_BUFFERS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_UNIFORM_LOCATIONS` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_ALU_INSTRUCTIONS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_TEX_INSTRUCTIONS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_TEX_INDIRECTIONS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_NATIVE_ALU_INSTRUCTIONS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_NATIVE_TEX_INSTRUCTIONS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_NATIVE_TEX_INDIRECTIONS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_FRAGMENT_UNIFORM_COMPONENTS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_FRAMEBUFFER_WIDTH` int(11) DEFAULT NULL,
  `GL_MAX_FRAMEBUFFER_HEIGHT` int(11) DEFAULT NULL,
  `GL_MAX_FRAMEBUFFER_LAYERS` int(11) DEFAULT NULL,
  `GL_MAX_FRAMEBUFFER_SAMPLES` int(11) DEFAULT NULL,
  `GL_NUM_PROGRAM_BINARY_FORMATS` int(11) DEFAULT NULL,
  `GL_MAX_IMAGE_UNITS` int(11) DEFAULT NULL,
  `GL_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS` int(11) DEFAULT NULL,
  `GL_MAX_VERTEX_IMAGE_UNIFORMS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS` int(11) DEFAULT NULL,
  `GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS` int(11) DEFAULT NULL,
  `GL_MAX_GEOMETRY_IMAGE_UNIFORMS` int(11) DEFAULT NULL,
  `GL_MAX_FRAGMENT_IMAGE_UNIFORMS` int(11) DEFAULT NULL,
  `GL_MAX_COMBINED_IMAGE_UNIFORMS` int(11) DEFAULT NULL,
  `GL_MAX_SPARSE_TEXTURE_SIZE_ARB` int(11) DEFAULT NULL,
  `GL_MAX_SPARSE_3D_TEXTURE_SIZE_ARB` int(11) DEFAULT NULL,
  `GL_MAX_SPARSE_ARRAY_TEXTURE_LAYERS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_SERVER_WAIT_TIMEOUT` int(11) DEFAULT NULL,
  `GL_NUM_COMPRESSED_TEXTURE_FORMATS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_MATRIX_STACK_DEPTH_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_MATRICES_ARB` int(11) DEFAULT NULL,
  `GL_MAX_VERTEX_ATTRIBS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_INSTRUCTIONS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_NATIVE_INSTRUCTIONS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_TEMPORARIES_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_NATIVE_TEMPORARIES_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_PARAMETERS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_NATIVE_PARAMETERS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_ATTRIBS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_NATIVE_ATTRIBS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_ADDRESS_REGISTERS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_NATIVE_ADDRESS_REGISTERS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_LOCAL_PARAMETERS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_PROGRAM_ENV_PARAMETERS_ARB` int(11) DEFAULT NULL,
  `GL_MAX_VIEWPORTS` int(11) DEFAULT NULL,
  `GL_MAX_DUAL_SOURCE_DRAW_BUFFERS` int(11) DEFAULT NULL,
  `GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT` int(11) DEFAULT NULL,
  `GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT` int(11) DEFAULT NULL,
  `GL_MAX_SHADER_COMPILER_THREADS_ARB` int(11) DEFAULT NULL,
  `GL_VIEWPORT_SUBPIXEL_BITS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ReportID`),
  KEY `ReportID` (`ReportID`),
  KEY `ReportId_desc` (`ReportID`),
  KEY `submissiondate` (`submissiondate`)
) ENGINE=MyISAM AUTO_INCREMENT=6507 DEFAULT CHARSET=latin1;

CREATE TABLE `openglcapslisting` (
  `name` varchar(255) NOT NULL,
  `identifier` int(11) DEFAULT NULL,
  `description` text,
  `version` text,
  PRIMARY KEY (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `openglextensions` (
  `PK` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`PK`),
  UNIQUE KEY `Name` (`Name`)
) ENGINE=MyISAM AUTO_INCREMENT=910 DEFAULT CHARSET=latin1;

CREATE TABLE `openglfeatures` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `extensionlist` varchar(1024) DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  PRIMARY KEY (`id`,`name`),
  UNIQUE KEY `name_UNIQUE` (`name`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

CREATE TABLE `openglgpuandext` (
  `ReportID` int(11) NOT NULL DEFAULT '0',
  `ExtensionID` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ExtensionID`,`ReportID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `openglnews` (
  `date` date NOT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `text` text,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=8 DEFAULT CHARSET=latin1;

CREATE TABLE `reportHistory` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `submitter` varchar(255) DEFAULT NULL,
  `log` text,
  `reportId` int(11) NOT NULL,
  PRIMARY KEY (`id`,`reportId`)
) ENGINE=MyISAM AUTO_INCREMENT=431 DEFAULT CHARSET=latin1;

CREATE TABLE `spirvextensions` (
  `reportid` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`reportid`,`name`),
  KEY `name` (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE ALGORITHM=UNDEFINED DEFINER=`DATABASE_NAME`@`%` SQL SECURITY DEFINER VIEW `viewCompressedFormats` AS select `enumTranslationTable`.`text` AS `text`,(((select count(distinct `compressedTextureFormats`.`reportId`) from `compressedTextureFormats` where (`compressedTextureFormats`.`formatEnum` = `enumTranslationTable`.`enum`)) / (select count(0) from `openglcaps`)) * 100) AS `coverage` from `enumTranslationTable` where `enumTranslationTable`.`enum` in (select distinct `compressedTextureFormats`.`formatEnum` from `compressedTextureFormats`);

CREATE ALGORITHM=UNDEFINED DEFINER=`DATABASE_NAME`@`%` SQL SECURITY DEFINER VIEW `viewDeviceMaxVersions` AS select `openglcaps`.`GL_RENDERER` AS `name`,`openglcaps`.`submissiondate` AS `date`,max(trim(left(`openglcaps`.`GL_VERSION`,3))) AS `maxversion`,max(`openglcaps`.`ReportID`) AS `repid` from `openglcaps` where (trim(left(`openglcaps`.`GL_VERSION`,3)) <> 'Ope') group by `name`;

CREATE ALGORITHM=UNDEFINED DEFINER=`DATABASE_NAME`@`%` SQL SECURITY DEFINER VIEW `viewExtensions` AS select `exts`.`Name` AS `name`,`exts`.`PK` AS `id`,(select count(distinct `oge`.`ReportID`) from `openglgpuandext` `oge` where (`oge`.`ExtensionID` = `exts`.`PK`)) AS `reports`,(select ((count(distinct `oge`.`ReportID`) / (select count(0) from `openglcaps`)) * 100) from `openglgpuandext` `oge` where (`oge`.`ExtensionID` = `exts`.`PK`)) AS `coverage` from `openglextensions` `exts` where (`exts`.`Name` <> '') order by `exts`.`Name`;

DELIMITER $$
CREATE DEFINER=`DATABASE_NAME`@`%` FUNCTION `cleanOsName`(osname char(255)) RETURNS char(255) CHARSET latin1
BEGIN
	DECLARE osclear char(255);
	SET osclear = osname;
    
    
	IF (Locate('Linux', osclear) > 0) AND ( Locate('-', osclear) > 0) then
		SET osclear = Left(osclear, Locate('-', osclear)-1);
	END IF;

	RETURN trim(osclear);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`DATABASE_NAME`@`%` FUNCTION `contextTypeName`(contextType char(32)) RETURNS char(32) CHARSET latin1
BEGIN	
	DECLARE ctxName char(32);
	SET ctxName = contextType;
	
	IF isnull(contextType) THEN
		SET ctxName = 'OpenGL';
	END IF;

	IF strcmp(ctxName, 'regular') = 0 THEN
		SET ctxName = 'OpenGL';
	END IF;
    
	IF strcmp(ctxName, 'default') = 0 THEN
		SET ctxName = 'OpenGL';
	END IF;    

	IF strcmp(ctxName, 'core') = 0 THEN
		SET ctxName = 'OpenGL Core';
	END IF;

	IF strcmp(ctxName, 'ES2') = 0 THEN
		SET ctxName = 'OpenGL ES 2.0';
	END IF;

	IF strcmp(ctxName, 'ES3') = 0 THEN
		SET ctxName = 'OpenGL ES 2.0';
	END IF;

	RETURN ctxName;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`DATABASE_NAME`@`%` FUNCTION `GL_RENDERER_CLEAR`(renderer varchar(512), vendor varchar(512)) RETURNS varchar(512) CHARSET latin1
BEGIN
	DECLARE rendererClear varchar(512);
	SET rendererClear = renderer;

	IF (Locate('ATI', vendor) > 0) or (Locate('AMD', vendor) > 0) then
		SET rendererClear = Replace(rendererClear, 'ATI', '');
		SET rendererClear = Replace(rendererClear, 'AMD', '');
		SET rendererClear = Replace(rendererClear, 'Series', '');
		SET rendererClear = Replace(rendererClear, 'Graphics', '');
		SET rendererClear = Replace(rendererClear, 'series', '');
		SET rendererClear = Replace(rendererClear, 'graphics', '');
		SET rendererClear = Replace(rendererClear, 'OpenGL Engine', '');
	END IF;

	IF Locate('NVIDIA', vendor) > 0 then
		set rendererClear = Replace(rendererClear, '/PCIe', '');
		set rendererClear = Replace(rendererClear, '/PCI', '');
		set rendererClear = Replace(rendererClear, '/SSE2', '');
		set rendererClear = Replace(rendererClear, '/3DNOW!', '');
		set rendererClear = Replace(rendererClear, '/SSE', '');
		set rendererClear = Replace(rendererClear, '/AGP', '');
		set rendererClear = Replace(rendererClear, 'NVIDIA', '');
	END IF;

	IF Locate('Intel', vendor) > 0 then
		set rendererClear = Replace(rendererClear, 'OpenGL Engine', '');
		set rendererClear = Replace(rendererClear, 'x86', '');
		set rendererClear = Replace(rendererClear, '/MMX', '');
		set rendererClear = Replace(rendererClear, '/SSE', '');
		set rendererClear = Replace(rendererClear, 'Intel(R)', '');
	END IF;


	RETURN trim(rendererClear);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`DATABASE_NAME`@`%` FUNCTION `GL_VENDOR_SHORT`(vendor varchar(512)) RETURNS varchar(512) CHARSET latin1
BEGIN
	DECLARE vendorShort varchar(512);
	SET vendorShort = '';

	IF (Locate('ATI', vendor) > 0) or (Locate('AMD', vendor) > 0) then
		SET vendorShort = 'ATI';
	END IF;

	IF Locate('NVIDIA', vendor) > 0 then
		set vendorShort = 'NVIDIA';
	END IF;

	IF Locate('Intel', vendor) > 0 then
		set vendorShort = 'INTEL';
	END IF;

	IF (vendorShort = '') THEN
		set vendorShort = 'OTHER';
	END IF;

	RETURN trim(vendorShort);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`DATABASE_NAME`@`%` FUNCTION `GL_VERSION_SHORT`(version varchar(512)) RETURNS varchar(512) CHARSET latin1
BEGIN
	DECLARE versionShort varchar(512);
	SET versionShort = version;

	SET versionShort = Replace(versionShort, 'Compatibility Profile Context', '');

	RETURN trim(versionShort);
END$$
DELIMITER ;
